const HANDLE_INPUT_CHANGE = 1;
const SET_LOADING = 2;
const HANDLE_INPUT_IMAGE = 3;
const CLEAR_FORM = 4;
const HANDLE_INPUT_CHANGE_PROFILE = 5;
const HANDLE_INPUT_CHANGE_ACCOUNT = 6;
const HANDLE_INPUT_CHANGE_ADDRESS = 7;
const HANDLE_FETCH = 8;
const HANDLE_INPUT_QUANTITY = 9;
const HANDLE_ADD_TO_CART = 10;
const HANDLE_DELETE_CART = 11;
const HANDLE_CHANGE_VOUCHER = 12;

export {
  HANDLE_INPUT_CHANGE,
  SET_LOADING,
  HANDLE_INPUT_IMAGE,
  CLEAR_FORM,
  HANDLE_INPUT_CHANGE_PROFILE,
  HANDLE_INPUT_CHANGE_ACCOUNT,
  HANDLE_INPUT_CHANGE_ADDRESS,
  HANDLE_FETCH,
  HANDLE_INPUT_QUANTITY,
  HANDLE_ADD_TO_CART,
  HANDLE_DELETE_CART,
  HANDLE_CHANGE_VOUCHER,
};
