const HANDLE_INPUT_CHANGES =1
const FETCH_COMPLETE = 2
const LOGIN =3
const LOGOUT =4
const RETRIEVE_TOKEN=5
const REGISTER=6
const SET_LOADING=7
const ADD_TO_CART=8
const REMOVE_FROM_CART=9

export {HANDLE_INPUT_CHANGES, FETCH_COMPLETE, LOGIN, LOGOUT, RETRIEVE_TOKEN, REGISTER, SET_LOADING, ADD_TO_CART, REMOVE_FROM_CART}
